### PR TITLE
Fixity Overhaul

### LINKED ISSUE #188: RepositoryAuditService audits not showing results in the UI
<a href="https://github.com/electrickite"></img></a> **Issue by [electrickite](https://github.com/electrickite)**
_Tuesday Nov 15, 2016 at 14:42 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2886_

----

### Descriptive summary

When running audits using `Sufia::RepositoryAuditService.audit_everything`, the results are not shown in the UI.

Observed in Sufia 7.0.0, but I can't see anything in later versions that would have changed this behavior.

### Expected behavior

Running audits on a `FileSet` will show the results of the audit on the file set show page.

### Actual behavior

The audit status remains 'Audits have not yet been run on this file.' even if audits have been run.

### Steps to reproduce the behavior

1. Create at least one Work with an attached FileSet
2. From a Rails console, run `Sufia::RepositoryAuditService.audit_everything`
3. If needed, wait for background audit jobs to complete.
4. From a Rails console, run `ChecksumAuditLog.all` and observe that audit log entries have been created.
5. Navigate to the FileSet "show" page and observe the audit status is still 'Audits have not yet been run on this file.'

### PR DESCRIPTION
**Pull request by jrochkind**
[The fixity-checking code was in kind of bad shape](https://bibwild.wordpress.com/2017/05/01/exploring-and-planning-with-sufiahyraxfedora-fixity-validation/)

On further analysis, I think much of it dated from both before FC4, and before part of it had been made an async ActiveJob. And while things were changed enough for tests to pass at that point, there was broken func ("fixity status" on FileSet show page passing tests cause they were mocked but not actually working); things not quite sensibly for a multi-file multi-version environment; API that didn't quite make sense for async; method params, db attributes and local vars that no longer accurately described what they were; and some crufty implementation. 

I tried to fix it all up, the interrelatedness of the classes means this is kind of a big PR, but I _tried_ to  do individual test-passing commits (not always succesfully). 

After this PR:

* "Fixity status" on FileSet show page actually shows fixity status. Taking account of the fact that there may be more than one binarystream involved (multiple versions and/or files), it's more than just a simple 'pass' or 'fail', especially in the (very very rare) case of 'fail', but I tried to fit it into the 180px column it was in (didn't want to mess with that page which others are [already](https://github.com/projecthydra-labs/hyrax/issues/106) [discussing](https://github.com/projecthydra-labs/hyrax/issues/121).  Closes #188 
  * Actual human readable message creation extracted to a new FixityStatusService

* The ChecksumAuditLog records being created will include `expected_result` _if_ [using an ActiveFedora that returns it](https://github.com/projecthydra/active_fedora/pull/1239) (`respond_to?` check). 

* The _pruning_ of old ChecksumAuditLog records could have been deleting too many, it's now multi-bytestream-per-fileset aware. 

* The `after_fixity_check_failure` hook was not actually passing enough info to know _what_ failed, in a multi-bytestream-per-fileset world. It now passes the ChecksumAuditLog record itself, with everything that's been recorded. (The actual action/message of the default FixityCheckFailureService is unchanged, but at least the right info is being passed for a different one)

* FileSetFixityCheckService has some options on init to:  run checks in foreground instead of async (only way to get immediate results); check latest version(s) only instead of all versions; override `max_days_between_fixity_checks` from global configuration. 

* Lots of arg name changes -- it was confusing what the args represented, in addition to renaming, made some of them keyword args so you have to pay attention to what it is you're passing. Lots of general code cleanup and modernization. 
    * The ChecksumAuditLog AR record has renamed/typed columns to accurately convey what they actually are -- didn't change what they were from previous code, just made it _work_ and be named educationally.  Including a `boolean` for "passed" rather than an integer that previously could also be `999` meaning, I guess, "in progress" -- that was not really neccessary. 
    * Lots more class-level and method-level docs explaining what things are meant to do. 

This code is definitely not _perfect_, there is lots of room for improvement. But after 2+ weeks figuring out what it did, what it was trying to do, what it should be trying to do, and making it so -- I _think_ it's good enough, working, and a good basis for future work someday. 

One thing I don't like is that the recorded `checked_uri` in ChecksumAuditLog (usually a version URI, but sometimes a file URI if the fcrepo does not have versions enabled, or the caller chooses to use it this way -- these semantics were inherited) is a uri, instead of a fedora `id` like the `file_set_id` and `file_id`. This could make it sensitive to hostname changes on the fedora server. But there just didn't seem to be any way to get an `id` out of what I had without other changes in other parts of the stack I didn't have the stomach for. 

UI things I'd like but haven't gotten to yet (and may not):

* I think the 'versions' tab on File/edit screen, which is the only place that lists "versions", probably ought to put a fixity status next to each version, since fixity checks are actually version-specific. 

* I think there ought to be an admin dashboard fixity status report, either on dashboard itself or a separate page or a combo of both, that lists any current _failing_ fixity checks, as well as general fixity status (range of dates latest fixity checks were made on, number of fixity checks, whatever). 

I'm hoping this is useful to Hyrax; I have limited time to make any major changes, but am happy to discuss the code. I will probably be backporting this to our local (sufia 7.3) app regardless of it's disposition here.

### CODE REVIEW

**Comment by jrochkind** [comment]
Hey @aeschylus et al, not sure what the 'in_progress' tag means, but I consider this ready for review/merge, and don't necessarily plan on doing more work on it. 

The things I mentioned as possible future improvements are, but I think this is acceptable for merge now and an improvement over what's there. 

Subject to consultation with reviewers of course, but i'm ready for it!

**Comment by jcoyne** [comment]
@jrochkind the `in_progress` tag is added by waffle.io and you can disregard it.

File: app/controllers/hyrax/fixity_checks_controller.rb [hunk 1]
```diff
@@ -2,15 +2,27 @@ module Hyrax
...
     def create
       render json: fixity_check_service.fixity_check
     end
 
     protected
 
       def fixity_check_service
-        file_set = ::FileSet.find(params[:file_set_id])
-        FileSetFixityCheckService.new(file_set)
+        @fixity_check_service ||=
```
Comment (jcoyne) [inline app/controllers/hyrax/fixity_checks_controller.rb]: Is this ever called more than once per request?   do we need to memoize?   Can you add documentation about why you are setting `async_jobs: false`

File: app/jobs/fixity_check_job.rb [hunk 2]
```diff
@@ -1,42 +1,63 @@
...
+  # be pruned.
+  #
+  # If calling async as a background job, return value is irrelevant, but
+  # if calling sync with `perform_now`, returns the ChecksumAuditLog
+  # record recording the check.
+  #
+  # @param uri [String] uri - of the specific file/version to fixity check
+  # @param file_set_id [FileSet] the id for FileSet parent object of URI being checked.
+  # @param file_id [String] File#id, used for logging/reporting.
+  def perform(uri, file_set_id:, file_id:)
```
Comment (jcoyne) [inline app/jobs/fixity_check_job.rb]: Changing the erasure of a method is a breaking change, so this should be for Hyrax, 2, right?  Do you think we need to deprecate the old interface?

File: app/models/checksum_audit_log.rb [hunk 3]
```diff
@@ -1,20 +1,49 @@
 class ChecksumAuditLog < ActiveRecord::Base
-  # TODO: this method doesn't seem to be used. Remove?
-  def self.fixity_check_log(id, path, version_uri)
```
Comment (jcoyne) [inline app/models/checksum_audit_log.rb]: should this method be deprecated before removal?

File: app/services/hyrax/file_set_fixity_check_service.rb [hunk 4]
```diff
@@ -1,9 +1,45 @@
...
     # @param file_set [ActiveFedora::Base, String] file_set
-    def initialize(file_set)
+    # @param async_jobs [Boolean] Run actual fixity checks in background. Default true.
+    # @param max_days_between_fixity_checks [int] if an exisitng fixity check is
+    #   recorded within this window, no new one will be created. Default
+    #   `Hyrax.config.max_days_between_fixity_checks`. Set to -1 to force
+    #    check.
+    # @param latest_version_only [Booelan]. Check only latest version instead of all
+    #   versions. Default false.
+    def initialize(file_set,
```
Comment (jcoyne) [inline app/services/hyrax/file_set_fixity_check_service.rb]: Changing the erasure of a public method. Do we need a deprecation?

File: app/services/hyrax/file_set_fixity_check_service.rb [hunk 5]
```diff
@@ -12,91 +48,54 @@ def initialize(file_set)
...
+    #
+    # If async_jobs is true (default), just returns nil, stuff is still going on.
+    def fixity_check
+      results = file_set.files.collect { |f| fixity_check_file(f) }
 
-    # provides a human readable version of the fixity check status
-    # This may trigger fixity checks if required
-    # @param [Hydra::PCDM::File] file the file to get the fixity check status for,
-    #                                 defaults to the original_file.
-    def human_readable_fixity_check_status(file = file_set.original_file)
```
Comment (jcoyne) [inline app/services/hyrax/file_set_fixity_check_service.rb]: Should this method be deprecated before removal?

File: app/services/hyrax/file_set_fixity_check_service.rb [hunk 6]
```diff
@@ -12,91 +48,54 @@ def initialize(file_set)
...
-        'Fixity checks have not yet been run on this file.'
-      end
+      results.flatten.group_by(&:file_id)
     end
 
-    # Fixity checks each version of each file if it hasn't been checked recently
-    # Returns the set of most recent fixity check status for each version of the
-    # content file
-    # @param [Hash] log container for messages, mapping file ids to status
-    def fixity_check(log = {})
```
Comment (jcoyne) [inline app/services/hyrax/file_set_fixity_check_service.rb]: Should this method be deprecated before removal?

File: app/services/hyrax/fixity_check_failure_service.rb [hunk 7]
```diff
@@ -1,9 +1,14 @@
 module Hyrax
   class FixityCheckFailureService < MessageUserService
-    attr_reader :log_date
+    attr_reader :log_date, :checksum_audit_log, :file_set
+
+    def initialize(file_set, checksum_audit_log:)
```
Comment (jcoyne) [inline app/services/hyrax/fixity_check_failure_service.rb]: Should the old interface to this method be deprecated?

File: app/services/hyrax/fixity_status_service.rb [hunk 8]
```diff
@@ -0,0 +1,86 @@
+module Hyrax
+  # Creates fixity status messages to display to user, for a fileset, or
+  # a specific version/file within it. Determines status by looking up
+  # existing ChecksumAuditLog objects, does not actually do a check itself.
+  # See FileSetFixityCheckService and ChecksumAuditLog for actually performing
+  # checks and recording as ChecksumAuditLog objects.
+  class FixityStatusService
+    include ActionView::Helpers::TagHelper
```
Comment (jcoyne) [inline app/services/hyrax/fixity_status_service.rb]: This to me seems like an odd include for a service object.  I would think that an object that emits HTML would be a presenter.

File: app/controllers/hyrax/fixity_checks_controller.rb (hunk 1 above)
Comment (jrochkind) [inline app/controllers/hyrax/fixity_checks_controller.rb]: I am in the habit of memoizing everything in a controller, so if it's later called more than once in a view, you just don't need to think about it. Does it hurt, or do you think this is a bad pattern in some way?

File: app/models/checksum_audit_log.rb (hunk 3 above)
Comment (jrochkind) [inline app/models/checksum_audit_log.rb]: In general re deprecations:  This stuff had to change so much that adding deprecations everywhere would be a major increase in complexity. I think that the former methods probably _were not used_ by anyone, because, well, they didn't really work.  So I guess I'm making the argument that the previous signatures and methods were effectively bugs. I am normally pretty pro-backwards-compat, but in this case, I don't think backwards compat with probably-unused broken architecture is a priority. 

I recognize other opinions may be reasonable though! But I don't know if I personally have time to go back and make sure all existing (public?) methods and signatures still work with deprecation.

File: app/services/hyrax/file_set_fixity_check_service.rb (hunk 4 above)
Comment (jrochkind) [inline app/services/hyrax/file_set_fixity_check_service.rb]: I assume you mean 'signature', not 'erasure'?  See above on my current attitude toward deprecation.  The previous signature was just too easy to be mis-used (and was being mis-used in existing code), it needed a new signature that was clearer on semantics and intent. 

I guess one could leave the signature the same (subject to misuse) for sake of backwards compat, but I think this would be unfortunate. Or one could add deprecation with previous signature working here and in other places, with significant increase in complexity of code. 

Originally I wanted to maintain backwards compat everywhere, but the more I got into it, the more I arrived at thinking this stuff had to be more drastically altered to have a transparent and clear API.

File: app/services/hyrax/fixity_status_service.rb (hunk 8 above)
Comment (jrochkind) [inline app/services/hyrax/fixity_status_service.rb]: I don't really understand the hydra architecture here.  I think I went with service object simply because it was before -- I separated out from one service object to another. And maybe I misunderstood a comment you made in slack that I thought was recommending extracting this to it's own service objects. 

Happy to change it to a 'presenter' object if you think that's better. I don't really understand the hydra 'presenter' architecture, can you share an analogous presenter object I can use as a guideline?  Can this still be it's _own_ presenter object that does nothing but status message, does that fit into the architecture?  I worry that trying to shoehorn this into some _existing_ presenter object that also does other stuff would be a bigger harm to backwards compat to people who have overridden that presenter object (as is encouraged I think?). 

While _most_ of the public API effected in this PR I think was not used by anyone, "display a fixity status message" of course is used in every sufia/hyrax app, and I tried to keep the code path to _that_ as backwards compat as possible (even leaving the cover method in FileSetFixityCheckService, for those who have presenters calling it).

File: app/controllers/hyrax/fixity_checks_controller.rb (hunk 1 above)
Comment (jrochkind) [inline app/controllers/hyrax/fixity_checks_controller.rb]: I can add docs about async:false. We can also discuss whether the design is wise. 

Basically, because async:false is the only way to be assured to get a response that you can return immediately. The alternative would be more complicated code that somehow returned "in progress" for bytestreams without a fresh fixity check record. 

I went with the simple approach in part because I don't believe this action is actually _used by anyone_.  It's not used by existing hyrax code so far as I can tell. I think it's a leftover from a previous (pre FC4 even?) version of sufia that used it for "fixity status" display, but it hasn't for a while. 

I wanted to leave the action here because it actually _does_ seem to useful to have an HTTP API on fixity status for external integration.  But I didn't want to spend _too_ much time on it making it _perfect_, when just guessing on use cases. 

Another alternative would be removing this action/controller altogether, which I'd also be open to.

**Comment by jrochkind** [comment]
I agree this could use a third set of eyes/opinions. Any suggestions as to who might be a good interested party?  @awead? @mjgiarlo?

File: app/services/hyrax/file_set_fixity_check_service.rb (hunk 6 above)
Comment (jrochkind) [inline app/services/hyrax/file_set_fixity_check_service.rb]: Thus method hasn't actually been removed, the git diff has just separated it from where it remains since there were so many changes to this file. It does now take no params instead of a `log` param of unclear utility that was not being used internally in hyrax.

File: app/services/hyrax/fixity_status_service.rb (hunk 8 above)
Comment (awead) [inline app/services/hyrax/fixity_status_service.rb]: I don't think of services as rendering any html. In fact, I don't even think presenters should render html... that's what views are for. However, if you need the ability to call this service to display html in different places, then I suppose this could be a good solution. Otherwise, I think a presenter/view combo would be better.

The problem with the html-service is that it's difficult to override. I can't define my own service and us it in place of this, I have to override the whole thing, and I might only need to make cosmetic changes, which suggests a view would be better. Our current pattern is to define presenters and services in the controller so one can override them and define their own there.

If you wanted to go with a presenter, then it's just a plain ruby class that encompasses a fixity status, whatever that is. If it's just a single record from the database table, then you might not need one and passing the AR object to the view is enough. If a "fixity status" is multiple records, or a single record with some logic anchored around it, then the presenter can take care of that and then the view receives the presenter object and renders its contents with the appropriate html tags, etc.

File: app/controllers/hyrax/fixity_checks_controller.rb (hunk 1 above)
Comment (jcoyne) [inline app/controllers/hyrax/fixity_checks_controller.rb]: I don't really care about the memoization, it just seemed unnecessary to me. I wanted to be sure I wasn't missing anything. I would like you to add a comment though.

File: app/services/hyrax/file_set_fixity_check_service.rb (hunk 4 above)
Comment (jcoyne) [inline app/services/hyrax/file_set_fixity_check_service.rb]: Yes, I'm using the wrong term. Signature is a better choice.

File: app/jobs/fixity_check_job.rb [hunk 9]
```diff
@@ -1,42 +1,63 @@
-class FixityCheckJob < Hyrax::ApplicationJob
```
Comment (jrochkind) [inline app/jobs/fixity_check_job.rb]: I meant to keep `< Hyrax::ApplicationJob`, if it's not there it came from a merge with master gone wrong.

**Comment by jcoyne** [comment]
@jrochkind I'd be 👍 if you move the `fixity_status_service.rb` to a presenter (or split it into two classes, one of which is a presenter).

> Happy to change it to a 'presenter' object if you think that's better. I don't really understand the hydra 'presenter' architecture, can you share an analogous presenter object I can use as a guideline? Can this still be it's own presenter object that does nothing but status message, does that fit into the architecture? I worry that trying to shoehorn this into some existing presenter object that also does other stuff would be a bigger harm to backwards compat to people who have overridden that presenter object (as is encouraged I think?).

Yes, a presenter object could be very narrowly scoped and we can have presenters nested by other presenters.  A presenter pattern is also called the view-model, so think of it as modeling the data and showing it to the user. Anything that is mostly about rendering strings and html is most likely a presenter.

**Comment by jrochkind** [comment]
@jcoyne do I understand right presenter would/could have almost the exact same API it has now, (`.new(FileSet)`, and `.file_set_fixity_status`), basically just be in a different part of the filesystem with a different class name? That's no problem and makes sense to me, I can do that.

**Comment by jcoyne** [comment]
@jrochkind yes. It sounds like we understand each other.

File: app/presenters/hyrax/fixity_status_presenter.rb [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+    def initialize(file_set_id)
+      @file_set_id = file_set_id
+    end
+
+    # Returns a html_safe string communicating fixity status checks,
+    # possibly on multiple files/versions.
+    def render_file_set_status
+      @file_set_status ||=
+        if relevant_log_records.empty?
+          "Fixity checks have not yet been run on this object"
```
Comment (mjgiarlo) [inline app/presenters/hyrax/fixity_status_presenter.rb]: There are some strings in this PR that I'd like to see handled via i18n, but this PR is big enough and has waited long enough that it's reasonable for this to be ticketed and worked on subsequently IMO.

**Comment by mjgiarlo** [comment]
Thank you for the contribution, @jrochkind!

**Comment by jrochkind** [comment]
Thanks @jcoyne / @mjgiarlo !  Can you clarify, will this be in Hyrax 1.0, or too late for that -- and I should expect it in next 1.x or 2.x?

I have no opinion, you guys know what's best, just will use the info to effect my planning, thanks! 

(And yep, I agree it oughta be i18n ideally -- but it wasn't i18n'd before either, and I just ran out of steam, especially since the text I put in to give a more complete report on failure got somewhat complex. Thanks @mjgiarlo!)

**Comment by jcoyne** [comment]
@jrochkind presently master is targeting 2.0, if you want it in 1.0, submit a PR that cherry-picks these commits to the `1-0-stable` branch.

**Comment by jrochkind** [comment]
> @jrochkind presently master is targeting 2.0, if you want it in 1.0, submit a PR that cherry-picks these commits to the 1-0-stable branch.


And yet, somehow these commits made it into 1.0.0 anyway. Without separate commits cherry-picking. I totally have no idea how to keep track of or predict these things.
