### PR TITLE
Change data from integer to boolean in db-independent way

### LINKED ISSUE #1035: Migration doesn't work on Postgres
```
 $ rake db:migrate
== 20170524170114 ChangeChecksumAuditLog: migrating ===========================
-- rename_column(:checksum_audit_logs, :version, :checked_uri)
   -> 0.0321s
-- change_column(:checksum_audit_logs, :pass, :boolean)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "pass" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING pass::boolean".
: ALTER TABLE "checksum_audit_logs" ALTER COLUMN "pass" TYPE boolean
/Users/jcoyne/workspace/hyku/db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb:5:in `change'
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  column "pass" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING pass::boolean".
: ALTER TABLE "checksum_audit_logs" ALTER COLUMN "pass" TYPE boolean
/Users/jcoyne/workspace/hyku/db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb:5:in `change'
PG::DatatypeMismatch: ERROR:  column "pass" cannot be cast automatically to type boolean
HINT:  You might need to specify "USING pass::boolean".
/Users/jcoyne/workspace/hyku/db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb:5:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by jrochkind**
previous migration from #984, postgres did not like.

This way could be slow, as it needs to fetch and save each object individually,
but I can't think of anything better.

Those who already generated this hyrax migration into a local app may have to manually
copy over the migration. If this hadn't been in a release yet, that wouldn't seem
like a problem -- but seems it made it into 1.0 somehow?

Fixes #1035

As a bonus, it's reversible now.

### CODE REVIEW

File: db/migrate/20170504192714_change_checksum_audit_log.rb [hunk 1]
```diff
@@ -1,8 +1,18 @@
 class ChangeChecksumAuditLog < ActiveRecord::Migration[5.0]
   def change
     rename_column :checksum_audit_logs, :version, :checked_uri
-    change_column :checksum_audit_logs, :pass, :boolean
-    rename_column :checksum_audit_logs, :pass, :passed
+    add_column    :checksum_audit_logs, :pass, :passed
```
Comment (jcoyne) [inline db/migrate/20170504192714_change_checksum_audit_log.rb]: should this be `add_column :checksum_audit_logs, :passed, :boolean`?

File: db/migrate/20170504192714_change_checksum_audit_log.rb [hunk 2]
```diff
@@ -1,8 +1,18 @@
...
+
+    reversible do |dir|
+      dir.up do
+        ChecksumAuditLog.find_each { |log| log.update!(passed: log.pass ) }
```
Comment (jcoyne) [inline db/migrate/20170504192714_change_checksum_audit_log.rb]: can we do `execute 'UPDATE checksum_audit_logs SET passed = (pass = 1)'`

**Comment by jrochkind** [comment]
thanks @jcoyne! Since we both worked on this, I guess neither of us can serve as a reviewer now?

A little bit of a bug in the review process IMO -- if you had much less efficiently told me exactly what you wanted to do and I had had time to do it, you could have reviewed, but by saving us both time and cooperating on it instead, we need a third party. Oh well. @mjgiarlo, have a minute to review this simple thing?
