### PR TITLE
Generated feature spec requires the default admin set

### LINKED ISSUE #922: Generated feature test only works if two or more works are generated.
It also fails because there is no admin set, so the user has no ability to create a work and then the button doesn't show up. The UI has a shortcut if there's only one generated work.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Comment out lines necessary if you have more than one work type.

Fixes #922

@projecthydra-labs/hyrax-code-reviewers

### CODE REVIEW

File: lib/generators/hyrax/work/templates/feature_spec.rb.erb [hunk 1]
```diff
@@ -3,7 +3,8 @@
 require 'rails_helper'
 include Warden::Test::Helpers
 
-RSpec.feature 'Create a <%= class_name %>' do
+# NOTE: If you generated more than one work, you have to set "js: true"
```
Comment (jrochkind) [inline lib/generators/hyrax/work/templates/feature_spec.rb.erb]: generated... where? In this spec I guess?

Comment (mjgiarlo) [inline lib/generators/hyrax/work/templates/feature_spec.rb.erb]: This feature spec is generated by Hyrax's work generator. This is telling you that if you have run the work generator more than once, set `js` to `true`.
