### PR TITLE
Fix default workflow strategy.

### LINKED ISSUE #364: Can't override WorkflowStrategy
### Descriptive summary

You should be able to set the WorkflowStrategy on the WorkflowFactory, but it's being overridden by the initializer defined in Hyrax's engine. Should just be able to update https://github.com/projecthydra-labs/hyrax/blob/master/lib/hyrax/engine.rb#L60 to be `||=`

However, it was definitely confusing that there's a default strategy in the factory (https://github.com/projecthydra-labs/hyrax/blob/master/lib/hyrax/engine.rb#L60), but it'll never get called - probably an artifact of Sufia behavior.

### PR DESCRIPTION
**Pull request by tpendragon**
We were originally setting this to a default and immediately overriding
it, which was a side effect of this behavior being in
CurationConcerns.

Closes #364.

### CODE REVIEW

File: app/services/hyrax/workflow/workflow_factory.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@ module Hyrax
   module Workflow
     class WorkflowFactory
       class_attribute :workflow_strategy
-      self.workflow_strategy = DefaultWorkflowStrategy
+      self.workflow_strategy = Hyrax::Workflow::WorkflowByAdminSetStrategy
```
Comment (mjgiarlo) [inline app/services/hyrax/workflow/workflow_factory.rb]: Two questions:

1. I wonder if this means we should also dump the `DefaultWorkflowStrategy` since it's no longer being used?
2. Update line 9 below?

Comment (tpendragon) [inline app/services/hyrax/workflow/workflow_factory.rb]: I think it's probably useful to provide, especially for CC migrators who may have gotten to CC 2.0 and not customized their workflow strategy. We had already customized it to support geo concerns.

Comment (tpendragon) [inline app/services/hyrax/workflow/workflow_factory.rb]: Fixed comment.
